version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/infra"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    groups:
      github-actions:
        patterns:
          - "*"
