🗃components:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/src/components/*
🖼layouts:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/src/layouts/*
          - frontend/src/styles/*
🧩types:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/src/types/*
          - frontend/src/env.d.ts
⚒libs:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/src/libs/*
📄pages:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/src/pages/*
🕵test:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/tests/*
🗺config:
  - changed-files:
      - any-glob-to-any-file:
          - .env.example
          - frontend/astro.config.mjs
          - frontend/src/consts.ts
          - frontend/.env.example
          - frontend/.eslintignore
          - frontend/.eslintrc.cjs
          - frontend/.gitattributes
          - frontend/.gitignore
          - frontend/.npmrc
          - frontend/.prettierignore
          - frontend/.prettierrc
          - frontend/.playwright-ct.config.ts
          - frontend/.playwright.config.ts
          - frontend/.postcss.config.cjs
          - frontend/.tailwind.config.cjs
          - frontend/stylelint.config.cjs
          - frontend/.tsconfig.json
          - frontend/.vite.config.ts
          - frontend/.vscode/*
🎁package:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/package.json
          - frontend/pnpm-lock.yaml
👗static:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/public/*
📄docs:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - frontend/README.md
          - backend/README.md
          - LICENSE

🐟infra:
  - changed-files:
      - any-glob-to-any-file:
          - compose.yml
          - compose-prod.yml
          - infra/*
          - .dockerignore

✈ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/*
          - .github/labeler.yml
