#
# 本番用
# dc -f compose-prod.yml up -d --build
#
services:
  ghost:
    image: ghost:6-alpine
    restart: always
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      # 恐ろしく脆弱なDB設定だがコンテナの外に出していないやつなので、これでOKとする
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      NODE_ENV: production
      url: ${BACKEND_API_URL}
    volumes:
      - ./backend/images:/var/lib/ghost/content/images
      - ./backend/data:/var/lib/ghost/content/data
      - ./backend/config.production.json:/var/lib/ghost/config.production.json
    user: "1000:1000"
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "logging=promtail"
    networks:
      - app-network

  astro:
    image: ghcr.io/usuyuki/usuyuki_blog_v2_astro:latest
    # build:
    #   context: ./frontend
    #   dockerfile: ../infra/prod/astro/Dockerfile
    # ports:
    #   - "1000:1000"
    restart: always
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: production
      GHOST_CONTENT_KEY: ${GHOST_CONTENT_KEY}
      GHOST_API_URL: ${GHOST_API_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      EXTERNAL_BLOGS: ${EXTERNAL_BLOGS}
      GHOST_FRONT_URL: ${GHOST_FRONT_URL}
      LOKI_URL: http://loki:3100
    user: "1000:1000"
    depends_on:
      - ghost
      - loki
    labels:
      - "logging=promtail"
    networks:
      - app-network

  db:
    image: mysql:8.4
    restart: always
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network

  tunnel:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    depends_on:
      - ghost
      - astro
    networks:
      - app-network

  loki:
    image: grafana/loki:3.6.5
    restart: always
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network

  grafana:
    image: grafana/grafana:12.3.3
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      GRAFANA_BASE_URL: ${GRAFANA_BASE_URL:-http://localhost:1002}
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - app-network

  alloy:
    image: grafana/alloy:latest
    restart: always
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki
    networks:
      - app-network

volumes:
  db-store:
  loki-data:
  grafana-storage:

networks:
  app-network:
    driver: bridge
