apiVersion: 1

contactPoints:
  - name: discord-webhook
    receivers:
      - uid: discord-webhook
        type: discord
        settings:
          url: "${DISCORD_WEBHOOK_URL}"
        disableResolveMessage: false
