apiVersion: 1

groups:
  - name: astro-alerts
    folder: General
    interval: 30s
    rules:
      - uid: astro-app-error
        title: Astro Application Error
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: loki
              uid: P8E80F9AEF21F6940
            model:
              expr: rate({app="astro", level="error"} [5m])
              refId: A
          - refId: C
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: __expr__
              uid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    type: query_result
                    params:
                      - A
                  reducer:
                    type: last
                    params: []
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 0m
        annotations:
          summary: Astro application error detected
          description: "Error detected in Astro application logs"
        labels:
          severity: critical
          service: astro

  - name: ghost-alerts
    folder: General
    interval: 30s
    rules:
      - uid: ghost-app-error
        title: Ghost Application Error
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: loki
              uid: P8E80F9AEF21F6940
            model:
              expr: rate({app="ghost", level="ERROR"} [5m])
              refId: A
          - refId: C
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: __expr__
              uid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    type: query_result
                    params:
                      - A
                  reducer:
                    type: last
                    params: []
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 0m
        annotations:
          summary: Ghost CMS error detected
          description: "Error detected in Ghost CMS logs"
        labels:
          severity: critical
          service: ghost