server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_logging']
        regex: promtail
        action: keep
      - source_labels: ['__meta_docker_container_name']
        target_label: container_name
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream
      - source_labels: ['__meta_docker_container_name']
        regex: '.*ghost.*'
        target_label: app
        replacement: ghost
      - source_labels: ['__meta_docker_container_name']
        regex: '.*astro.*'
        target_label: app
        replacement: astro
    pipeline_stages:
      - match:
          selector: '{app="astro"}'
          stages:
            - regex:
                expression: '^(?P<level>error):'
            - labels:
                level:
            - regex:
                expression: '^(?P<level>info):'
            - labels:
                level:
            - regex:
                expression: '^(?P<level>warn):'
            - labels:
                level:
            - regex:
                expression: '"logType":"(?P<log_type>[^"]*)"'
            - labels:
                log_type:
      - match:
          selector: '{app="ghost"}'
          stages:
            - regex:
                expression: '\] (?P<level>ERROR|INFO|WARN) '
            - labels:
                level: